version: "3.8"
name: kratos

services:
  backend:
    container_name: kratos_backend
    build:
      context: .
      dockerfile: Dockerfile_Backend
    image: kratos_backend_image
    working_dir: /Backend
    volumes:
      - ./Backend:/Backend
    ports:
      - "9599:9599"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9599 --reload
    networks:
      - kratos-network

  frontend:
    container_name: kratos_frontend
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    image: kratos_frontend_image
    working_dir: /Frontend
    volumes:
      - ./Frontend:/Frontend
      - /Frontend/node_modules
    ports:
      - "9598:9598"
    environment:
      - NG_CLI_ANALYTICS=false
    command: npm start
    networks:
      - kratos-network
    depends_on:
      - backend

networks:
  kratos-network:
    driver: bridge
