FROM python:3.11.9-alpine

WORKDIR /Backend

COPY ./Backend/requirements.txt /code/Backend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/Backend/requirements.txt

ENTRYPOINT ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]