FROM node:22

WORKDIR /usr/src/app

RUN npm install -g @angular/cli

COPY ./Frontend/package.json ./Frontend/package-lock.json ./

RUN npm install

COPY ./Frontend ./

RUN npm run build

EXPOSE 3030

CMD ng serve --host 0.0.0.0 --port 3030
