FROM python:3.11-slim

WORKDIR /Backend

COPY ./Backend/requirements.txt /code/Backend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/Backend/requirements.txt

ENTRYPOINT ["uvicorn"]