name: kratos_api

services:
  api:
    container_name: kratos_container
    build: .
    image: kratos_image
    working_dir: /api
    volumes:
      - .:/api
    ports:
      - 8080:8080
    environment:
      - WATCHFILES_FORCE_POLLING=true
    restart: on-failure
