name: Test & Build

on:
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: kratos_image
  DOCKER_CONTAINER_NAME: kratos_container

jobs:
  test-python:
    name: Test Python Code
    strategy:
      matrix:
        python-version: [3.11.9]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Tests
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: pylint --load-plugins pylint_pydantic --extension-pkg-whitelist='pydantic' ./app --rcfile=.pylintrc
      - name: Run Tests
        run: python -m pytest

  build:
    name: Build Backend Docker Image
    needs: [test-python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t $DOCKER_IMAGE_NAME ./Backend
